version: '3.8'

services:
  main:
    build:
      context: ./service/
      dockerfile: Dockerfile
    command: gunicorn -w 4 -b 0.0.0.0:5000 manage:app  # Use Gunicorn in production
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=production
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/

volumes:
  postgres_data_prod:
