version: '3.8'

services:
  main:
    command: pytest  # Run your tests automatically
    environment:
      - FLASK_ENV=testing
    volumes:
      - ./service:/usr/src/app
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data_test:/var/lib/postgresql/data/

volumes:
  postgres_data_test:
